export const LOADING_SWITCH = "LOADING_SWITCH";
export const ADD_SEARCH_RESULTS = "ADD_SEARCH_RESULTS";
export const FLUSH_SEARCH_RESULTS = "FLUSH_SEARCH_RESULTS";
export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
